print("        Curriculum Vitae")
print("")
print("Nume: Mandrescu Stefan")
print("Nascut: 14.01.2004")
print("Elev al clasei a X-a `C`")
print("Profil real")
print("")
print("        Date de contact:")
print("")
print("e-mail: stefanmandrescu1401@gmail.com")
print("Numar de telefon: 012345678")
print("Adresa: str.Libertatii 13")
print("")
print("        Despre mine:")
print("")
print("Obiectiv: Extinderea cunostintelor in programare")
print("Sunt interesat de programare, pentesting si construire hardware")
print("")
print("        Abilitati si copetente:")
print("")
print("Cunosc limbajul de programare C#")

